name: hybrid_hex_color_converter
description: "Hybrid hex Color, Allows you to convert hexadecimal strings into flutters Color property and vice versa"
version: 0.0.2
homepage: https://rudo.es/
repository: https://github.com/rudoapps/hybrid_hex_color_converter.git
issue_tracker: https://github.com/rudoapps/hybrid_hex_color_converter/issues
topics:
 - colors
 - hexadecimal
 - hex
 - color
 
 
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
